"""chenge id_art column to not unique 

Revision ID: 016478ddf8c6
Revises: e99c1cb9e014
Create Date: 2023-05-08 18:42:29.966742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016478ddf8c6'
down_revision = 'e99c1cb9e014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opart', schema=None) as batch_op:
        batch_op.drop_constraint('opart_id_art_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opart', schema=None) as batch_op:
        batch_op.create_unique_constraint('opart_id_art_key', ['id_art'])

    # ### end Alembic commands ###
