"""create operation table ad references

Revision ID: 36b5fb78de87
Revises: aa730639c6d2
Create Date: 2023-05-04 18:11:14.987217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b5fb78de87'
down_revision = 'aa730639c6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typeop',
    sa.Column('id_top', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num_mask', sa.String(length=10), nullable=False),
    sa.Column('last_num', sa.Integer(), nullable=False),
    sa.Column('lastdate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_top'),
    sa.UniqueConstraint('last_num'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('num_mask')
    )
    op.create_table('operation',
    sa.Column('id_op', sa.Integer(), nullable=False),
    sa.Column('id_top', sa.Integer(), nullable=False),
    sa.Column('id_wso', sa.Integer(), nullable=True),
    sa.Column('id_wsi', sa.Integer(), nullable=True),
    sa.Column('opnumber', sa.String(length=20), nullable=False),
    sa.Column('opdate', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('opsum', sa.Float(), nullable=False),
    sa.Column('lastdate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_top'], ['typeop.id_top'], name='fk_operation_id_top'),
    sa.ForeignKeyConstraint(['id_wsi'], ['warehouse.id_ws'], name='fk_operation_id_wsi'),
    sa.ForeignKeyConstraint(['id_wso'], ['warehouse.id_ws'], name='fk_operation_id_wso'),
    sa.PrimaryKeyConstraint('id_op')
    )
    op.create_table('opstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_top', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_top'], ['typeop.id_top'], name='fk_opstatus_id_top'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opstatus')
    op.drop_table('operation')
    op.drop_table('typeop')
    # ### end Alembic commands ###
