"""create artbarcode table

Revision ID: 3edf936746e5
Revises: d10a5ea9cba5
Create Date: 2023-05-14 14:36:01.935548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edf936746e5'
down_revision = 'd10a5ea9cba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_barcode',
    sa.Column('barcode_id', sa.Integer(), nullable=False),
    sa.Column('id_art', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_art'], ['article.id_art'], name='fk_art_barcode_id_art'),
    sa.PrimaryKeyConstraint('barcode_id'),
    sa.UniqueConstraint('barcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_barcode')
    # ### end Alembic commands ###
