"""chenge lust_num column to not unique 

Revision ID: 9c0d38445a8c
Revises: df5a9f77332d
Create Date: 2023-05-08 11:18:38.954535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d38445a8c'
down_revision = 'df5a9f77332d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typeop', schema=None) as batch_op:
        batch_op.drop_constraint('typeop_last_num_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typeop', schema=None) as batch_op:
        batch_op.create_unique_constraint('typeop_last_num_key', ['last_num'])

    # ### end Alembic commands ###
