"""create unique constr to opart table

Revision ID: a6585e981aa1
Revises: 016478ddf8c6
Create Date: 2023-05-09 18:43:31.771193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6585e981aa1'
down_revision = '016478ddf8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opart', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_id_op_id_art', ['id_op', 'id_art'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opart', schema=None) as batch_op:
        batch_op.drop_constraint('unique_id_op_id_art', type_='unique')

    # ### end Alembic commands ###
