"""add price buy and sale to article

Revision ID: d10a5ea9cba5
Revises: a6585e981aa1
Create Date: 2023-05-13 20:23:47.058166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10a5ea9cba5'
down_revision = 'a6585e981aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_buy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_sale', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('price_sale')
        batch_op.drop_column('price_buy')

    # ### end Alembic commands ###
