"""create opart table

Revision ID: df5a9f77332d
Revises: ea6eb5af99f8
Create Date: 2023-05-06 13:06:30.136173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5a9f77332d'
down_revision = 'ea6eb5af99f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opart',
    sa.Column('id_opart', sa.Integer(), nullable=False),
    sa.Column('id_op', sa.Integer(), nullable=False),
    sa.Column('id_art', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('opsum', sa.Float(), nullable=False),
    sa.Column('lastdate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_art'], ['article.id_art'], name='fk_opart_id_art'),
    sa.ForeignKeyConstraint(['id_op'], ['operation.id_op'], name='fk_opart_id_op'),
    sa.PrimaryKeyConstraint('id_opart'),
    sa.UniqueConstraint('id_art')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opart')
    # ### end Alembic commands ###
