"""chenge typeio column to not unique 

Revision ID: e99c1cb9e014
Revises: 9c0d38445a8c
Create Date: 2023-05-08 14:07:29.784848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c1cb9e014'
down_revision = '9c0d38445a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typeop', schema=None) as batch_op:
        batch_op.drop_constraint('typeop_typeio_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typeop', schema=None) as batch_op:
        batch_op.create_unique_constraint('typeop_typeio_key', ['typeio'])

    # ### end Alembic commands ###
